[project]
name = "genai"
version = "0.1.0"
license = {file = "LICENSE"}
description = "GenAI LinkedIn Post Writer"
readme = "README.md"
requires-python = ">=3.13"

authors =  [
    {name = "Oliver Angelil", email = "oliver@ishango.ai"},
    {name = "Vincent Frimpong", email = "vincent@ishango.ai"}
]

dependencies = [
    "numpy>=2.2.2",
    "pyright>=1.1.393",
    "pytest>=8.3.4",
    "ruff>=0.9.5",
    "scipy>=1.15.1",
]

[project.urls]
Homepage = "https://ishango.ai/"

[project.scripts]
genai = "genai.source:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-vv -cov"

[tool.pyright]
exclude = []
typeCheckingMode = "basic"
reportUntypedFunctionDecorator = false
reportMissingTypeStubs = false
colorOutput = true

[tool.ruff]
line-length = 120
select = ["E", "F", "W", "C90"]
#ignore = ["E501"]

[tool.ruff.lint]
preview = true

#not sure what this does yet:
#[tool.ruff.format]
#preview = true

[tool.uv]
package = true
