name: Code Checks

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

permissions:
  contents: read

jobs:
  run-code-checks:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      
    - name: install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.29"

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: install package
      run: uv pip install .
      
    - name: run ruff code checks
      run: ruff check

    # - name: run ruff code checks
    #   run: uvx ruff@0.9.5 check

    # - name: run pyright type-hinting checks
    #   run: uvx pyright@1.1.394
  
    - name: run pyright type-hinting checks
      run: pyright

    - name: Run pytest
      run: pytest

    # - name: Run pytest
    #   run: uvx pytest@8.3.4

    - name: list python packages
      run: uv pip list
        
