name: Show Me the S3cr3tz
on:
  pull_request:
    branches: [ development ]
  
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up secret file

      run: |
        echo ${{secrets.GEMINI_API_KEY}} | sed 's/./& /g'
