name: OpenTofu Plan

on:
  pull_request:
    branches:
      - development
    paths:
      - 'opentofu/**.tf'
      - 'opentofu/**.tfvars'

jobs:
  tofu_plan:
    name: OpenTofu Plan
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/427938065788/locations/global/workloadIdentityPools/linkedin-genai-pool/providers/github'
          service_account: 'linkedin-genai-service@linkedin-genai.iam.gserviceaccount.com'

      # - name: Configure gcloud
      #   run: |
      #     gcloud config set project linkedin-genai



      - name: Tofu Init
        run: tofu init
        working-directory: opentofu

      # - name: unlock
      #   run: |                     
      #     tofu force-unlock -force 1741771029517362

      - name: Tofu Format
        run: tofu fmt -check
        working-directory: opentofu

      - name: Tofu Plan
        run: tofu plan -var="billing_account=${{ secrets.BILLING_ACCOUNT }}" -var="org_id=${{ secrets.ORG_ID }}"
        working-directory: opentofu
        env:
          TF_LOG: trace
